import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  ar: {
    appName: 'Gaming Your Way to Recovery',
    tagline: 'العب طريقك نحو التعافي',
    welcomeBack: 'أهلاً بعودتك،',
    yourJourney: 'رحلة تعافيك مستمرة',
    dailyGoal: 'الهدف اليومي',
    complete: 'مكتمل',
    morningStretch: 'تمارين الصباح',
    physicalTherapy: 'العلاج الطبيعي',
    eveningWalk: 'المشي المسائي',
    done: 'تم',
    inProgress: 'جاري التنفيذ',
    progressRoadmap: 'خارطة التقدم',
    initialAssessment: 'التقييم الأولي',
    strengthBuilding: 'بناء القوة',
    mobilityTraining: 'تدريب الحركة',
    independence: 'الاستقلالية',
    moodCheckIn: 'تقييم المزاج',
    howFeeling: 'كيف تشعر اليوم؟',
    great: 'رائع',
    okay: 'جيد',
    struggling: 'أحتاج دعم',
    home: 'الرئيسية',
    therapy: 'العلاج',
    community: 'المجتمع',
    reports: 'التقارير',
    todaysSession: 'جلسة اليوم',
    physicalTherapyExercises: 'تمارين العلاج الطبيعي',
    standingStability: 'ثبات الوقوف',
    minutes: 'دقيقة',
    clickToStart: 'اضغط لبدء التمرين',
    instructions: 'التعليمات',
    allExercises: 'جميع التمارين',
    seatedLegExtensions: 'تمديد الساق جالساً',
    armReachBalance: 'التوازن ومد الذراع',
    gaitTraining: 'تدريب المشي',
    communityGallery: 'معرض المجتمع',
    storiesOfHope: 'قصص الأمل والشفاء',
    story: 'قصة',
    artwork: 'عمل فني',
    shareYourJourney: 'شارك رحلتك',
    shareDescription: 'قصتك قد تلهم الآخرين. شارك تقدمك وفنك وكلمات التشجيع.',
    createPost: 'إنشاء منشور',
    recoveryAnalytics: 'تحليلات التعافي',
    patient: 'المريض',
    period: 'الفترة',
    downloadReport: 'تحميل التقرير',
    totalSessions: 'إجمالي الجلسات',
    improvement: 'التحسن',
    milestones: 'الإنجازات',
    mobilityProgress: 'تقدم الحركة',
    exerciseCompletion: 'إكمال التمارين',
    functionalAbility: 'القدرة الوظيفية',
    clinicalNotes: 'الملاحظات السريرية',
    actualScore: 'النتيجة الفعلية',
    targetGoal: 'الهدف المستهدف',
    completed: 'مكتمل',
    total: 'الإجمالي',
    currentAbility: 'القدرة الحالية',
    baseline: 'خط الأساس',
    mobility: 'الحركة',
    strength: 'القوة',
    balance: 'التوازن',
    endurance: 'التحمل',
    coordination: 'التنسيق',
    loadingJourney: 'جاري تحميل رحلتك...',
    nursingSupport: 'الدعم التمريضي',
    requestNurse: 'طلب ممرض/ة',
    nurseVisit: 'زيارة تمريضية',
    scheduleVisit: 'جدولة زيارة',
    nextVisit: 'الزيارة القادمة',
    yourNurse: 'الممرض/ة المسؤول',
    contactNurse: 'التواصل مع التمريض',
    nursingTeam: 'فريق التمريض المجتمعي',
    chatbotName: 'مساعد التعافي',
    chatbotGreeting: 'مرحباً! أنا مساعدك الذكي للتعافي. اسألني عن ملخص جلستك!',
    chatbotPlaceholder: 'اكتب رسالتك...',
    chatbotSend: 'إرسال',
    chatbotTyping: 'يكتب...',
    gaitGame: 'لعبة وضعية المشي',
    gameSubtitle: 'العب لتحسين وضعية مشيتك',
    gameDescription: 'أمام الكاميرا، المدرب الذكي يراقب ركبتيك ويرشدك أثناء المشي',
    startGame: 'ابدأ اللعبة',
    endGame: 'إنهاء الجلسة',
    toggleVoice: 'تبديل الصوت',
    waitingPose: 'ابتعد قليلاً حتى تظهر ملامح جسمك...',
    gameHint: 'اضغط ابدأ اللعبة ثم قف أمام الكاميرا',
    aiSummary: 'الملخص الذكي',
    generating: 'جاري التوليد...',
    sessionDuration: 'مدة الجلسة',
    avgPostureAngle: 'متوسط زاوية الوضعية',
    redAlerts: 'تنبيهات الخطورة',
    gaitTrend: 'تطور وضعية المشي',
    postureAngle: 'زاوية الوضعية',
    targetAngle: 'الزاوية المستهدفة',
    min: 'أدنى',
    max: 'أعلى',
    noSessions: 'لا توجد جلسات مسجلة بعد. العب جلسة من صفحة العلاج أولاً.',
    backendOffline: 'الخادم غير متصل (شغّل uvicorn على المنفذ 8001)',
    latestSession: 'آخر جلسة',
    y3172Pipeline: 'خط أنابيب الاتحاد الدولي للاتصالات Y.3172',
    pipelineTrace: 'تتبع خط الأنابيب',
    inTransit: 'حزمة قيد العبور',
    idleRun: 'خامل — شغّل الملخص الذكي',
    runPipeline: 'تشغيل خط الأنابيب',
    src: 'المصدر',
    c: 'المجمع',
    pp: 'المعالجة',
    m: 'النموذج',
    p: 'السياسة',
    d: 'التوزيع',
    sink: 'الوجهة',
    sources: 'المصادر',
  },
  en: {
    appName: 'Gaming Your Way to Recovery',
    tagline: 'Level up your rehabilitation journey',
    welcomeBack: 'Welcome Back,',
    yourJourney: 'Your recovery journey continues',
    dailyGoal: 'Daily Goal',
    complete: 'complete',
    morningStretch: 'Morning stretch',
    physicalTherapy: 'Physical therapy',
    eveningWalk: 'Evening walk',
    done: 'Done',
    inProgress: 'In progress',
    progressRoadmap: 'Progress Roadmap',
    initialAssessment: 'Initial Assessment',
    strengthBuilding: 'Strength Building',
    mobilityTraining: 'Mobility Training',
    independence: 'Independence',
    moodCheckIn: 'Mood Check-in',
    howFeeling: 'How are you feeling today?',
    great: 'Great',
    okay: 'Okay',
    struggling: 'Struggling',
    home: 'Home',
    therapy: 'Therapy',
    community: 'Community',
    reports: 'Reports',
    todaysSession: "Today's Session",
    physicalTherapyExercises: 'Physical Therapy Exercises',
    standingStability: 'Standing Stability',
    minutes: 'minutes',
    clickToStart: 'Click to start exercise',
    instructions: 'Instructions',
    allExercises: 'All Exercises',
    seatedLegExtensions: 'Seated Leg Extensions',
    armReachBalance: 'Arm Reach & Balance',
    gaitTraining: 'Gait Training',
    communityGallery: 'Community Gallery',
    storiesOfHope: 'Stories of hope, art, and healing',
    story: 'Story',
    artwork: 'Artwork',
    shareYourJourney: 'Share Your Journey',
    shareDescription: 'Your story can inspire others. Share your progress, artwork, or words of encouragement.',
    createPost: 'Create Post',
    recoveryAnalytics: 'Recovery Analytics',
    patient: 'Patient',
    period: 'Period',
    downloadReport: 'Download Report',
    totalSessions: 'Total Sessions',
    improvement: 'Improvement',
    milestones: 'Milestones',
    mobilityProgress: 'Mobility Progress',
    exerciseCompletion: 'Exercise Completion',
    functionalAbility: 'Functional Ability Assessment',
    clinicalNotes: 'Clinical Notes',
    actualScore: 'Actual Score',
    targetGoal: 'Target Goal',
    completed: 'Completed',
    total: 'Total',
    currentAbility: 'Current Ability',
    baseline: 'Baseline',
    mobility: 'Mobility',
    strength: 'Strength',
    balance: 'Balance',
    endurance: 'Endurance',
    coordination: 'Coordination',
    loadingJourney: 'Loading your journey...',
    nursingSupport: 'Nursing Support',
    requestNurse: 'Request Nurse',
    nurseVisit: 'Nurse Visit',
    scheduleVisit: 'Schedule Visit',
    nextVisit: 'Next Visit',
    yourNurse: 'Your Nurse',
    contactNurse: 'Contact Nurse',
    nursingTeam: 'Community Nursing Team',
    chatbotName: 'Recovery Assistant',
    chatbotGreeting: "Hi! I'm your smart recovery assistant. Ask me about your session summary!",
    chatbotPlaceholder: 'Type your message...',
    chatbotSend: 'Send',
    chatbotTyping: 'Typing...',
    gaitGame: 'Gait Posture Game',
    gameSubtitle: 'Play to improve your walking posture',
    gameDescription: 'In front of the camera, the AI coach watches your knees and guides you as you walk',
    startGame: 'Start Game',
    endGame: 'End Session',
    toggleVoice: 'Toggle voice',
    waitingPose: 'Step back until your body landmarks appear...',
    gameHint: 'Press Start Game and stand in front of the camera',
    aiSummary: 'AI Summary',
    generating: 'Generating...',
    sessionDuration: 'Session Duration',
    avgPostureAngle: 'Avg Posture Angle',
    redAlerts: 'Risk Alerts',
    gaitTrend: 'Gait Posture Trend',
    postureAngle: 'Posture angle',
    targetAngle: 'Target angle',
    min: 'Min',
    max: 'Max',
    noSessions: 'No sessions recorded yet. Play a session from the Therapy page first.',
    backendOffline: 'Backend offline (run uvicorn on port 8001)',
    latestSession: 'Latest session',
    y3172Pipeline: 'ITU-T Y.3172 Pipeline',
    pipelineTrace: 'Pipeline trace',
    inTransit: 'PACKET IN TRANSIT',
    idleRun: 'IDLE — RUN AI SUMMARY',
    runPipeline: 'Run Pipeline',
    src: 'Source',
    c: 'Collector',
    pp: 'Preprocessor',
    m: 'Model',
    p: 'Policy',
    d: 'Distributor',
    sink: 'Sink',
    sources: 'Sources',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('ar');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'ar' ? 'en' : 'ar');
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.ar] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      <div dir={language === 'ar' ? 'rtl' : 'ltr'} className={language === 'ar' ? 'font-arabic' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
